pull_request_rules:
    - name: backport patches to stable branch
      conditions:
      - base=test-master
      actions:
        backport:
          title: "[BACKPORT][{{ destination_branch }}] {{ title }}"
          body: |
            This is an automatic backport of pull request #{{number}}.
            
            {{cherry_pick_error}}
          assignees:
          - "{{ author }}"