#!/bin/bash -e

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"
PACKAGE_HARVESTER_UPGRADE_DIR="${TOP_DIR}/package/harvester-upgrade"

source ${SCRIPTS_DIR}/version

HARVESTER_OS_IMAGE="rancher/harvester-os:$VERSION"
HARVESTER_UPGRADE_IMAGE=rancher/harvester-upgrade:$VERSION

echo ${HARVESTER_OS_IMAGE}

cd ${PACKAGE_HARVESTER_UPGRADE_DIR}
docker build \
	--build-arg HARVESTER_OS_IMAGE="$HARVESTER_OS_IMAGE" \
	-t ${HARVESTER_UPGRADE_IMAGE} .
